INSERT INTO games (name, game_console, description, preview_link)
VALUES
('Ведьмак 3: Дикая Охота','PlayStation 4' ,'The Witcher 3: Wild Hunt — мультиплатформенная компьютерная ролевая игра с открытым миром, разработанная польской студией CD Projekt RED.', 'https://www.igromania.ru/game/14931/Vedmak_3_Dikaya_Ohota.html'),
('The Last of Us Part II','PlayStation 4' ,'The Last of Us Part II — компьютерная игра в жанре survival horror с элементами action и adventure, разработанная американской студией Naughty Dog.', 'https://www.igromania.ru/article/30927/The_Last_of_Us_Part_II_obzor_igry.html'),
('Red Dead Redemption 2','PlayStation 4' ,'Red Dead Redemption 2 — мультиплатформенная видеоигра, разработанная студией Rockstar Games.', 'https://www.igromania.ru/game/22747/Red_Dead_Redemption_2.html'),
('Assassin''s Creed: Вальгалла','PlayStation 4' ,'Assassin''s Creed Valhalla — мультиплатформенная компьютерная игра в жанре Action/RPG, разработанная студией Ubisoft Montreal.', 'https://www.igromania.ru/article/31490/Obzor_Assassin''s_Creed_Valhalla._Po_usam_teklo_a_v_rot_ne_popalo.html'),
('Cyberpunk 2077','PlayStation 4' ,'Cyberpunk 2077 — мультиплатформенная компьютерная игра в жанре action/RPG, разработанная польской студией CD Projekt RED.', 'https://www.igromania.ru/article/31511/Obzor_Cyberpunk_2077._U_CD_Projekt_Red_poluchilos.html'),
('Horizon Zero Dawn','PlayStation 4' ,'Horizon Zero Dawn — компьютерная игра в жанре Action/RPG, разработанная нидерландской студией Guerrilla Games', 'https://www.igromania.ru/article/28739/Strana_vechnoy_ohoty._Obzor_Horizon_Zero_Dawn.html'),
('God of War','PlayStation 4' ,'God of War — мультиплатформенная компьютерная игра в жанре Action, разработанная студией Santa Monica Studio', 'https://www.igromania.ru/article/30061/God_of_War._Mesto_pod_sosnami.html'),
('Uncharted 4: Путь вора','PlayStation 4' ,'Uncharted 4: Путь вора — компьютерная игра в жанре action-adventure, разработанная студией Naughty Dog', 'https://www.igromania.ru/article/27773/Odin_posledniy_raz._Obzor_Uncharted_4_Put_vora.html'),
('Death Stranding','PlayStation 4' ,'Death Stranding — мультиплатформенная компьютерная игра в жанре Action, разработанная японским режиссёром Хидэо Кодзимой', 'https://www.igromania.ru/article/31063/Obzor_Death_Stranding._Samyy_dorogoy_prank_v_istorii_igrovoy_industrii.html'),
('Bloodborne','PlayStation 4' ,'Bloodborne — мультиплатформенная компьютерная игра в жанре Action/RPG, разработанная японской студией From Software.', 'igromania.ru/article/26418/Sizif_podnimaetsya_na_Fudziyamu._Obzor_Bloodborne.html'),
('Minecraft: Story Mode','PlayStation 4' ,'В этой игре, состоящей из пяти частей, вы будете играть "Jesse" и отправитесь в опасное приключение через Рай, через Nether, к самому краю мира и за его пределы.', 'https://www.igromania.ru/game/19280/Minecraft_Story_Mode.html' ),
('Call of Duty: Warzone','PlayStation 4' , 'Это онлайн-шутер, в котором игроки борются за выживание на огромной карте, используя различное оружие и технику.', 'https://www.igromania.ru/game/374972/Call_of_Duty_Warzone.html' ),
('Assassin''s Creed: Одиссея','PlayStation 4', 'Это игра в жанре action-adventure, действие которой происходит в Древней Греции.', 'https://www.igromania.ru/game/30811/Assassin''s_Creed_Odyssey.html'),
('FIFA 21','PlayStation 4', 'Это игра в жанре спортивных симуляторов, посвященных футболу.','igromania.ru/article/31381/FIFA_21._Nikakogo_nekst-gena._Vpechatleniya_s_zakrytoy_prezentacii.html'),
('GTA V','PlayStation 4' ,'Это игра в жанре action-adventure, действие которой происходит в вымышленном городе Лос-Сантос.', 'https://www.igromania.ru/article/24114/Grand_Theft_Auto_5_Troe_iz_Los-Santosa._Geroi_GTA_5_v_realnoy_zhizni.html' ),
('Need for Speed: Heat','PlayStation 4' ,'Это игра в жанре аркадных гонок, действие которой происходит в вымышленном мире Палм-Сити.', 'https://www.igromania.ru/article/31080/Obzor_Need_for_Speed_Heat._Action-RPG_kotoraya_pritvorilas_gonkoy.html');